/* eslint-disable @typescript-eslint/no-unused-vars */
let erechim,
  palmeiraDasMissoes,
  capaoDaCanoa,
  bage,
  bentoGoncalves,
  cachoeiraDoSul,
  canoas,
  carazinho,
  caxiasDoSul,
  cruzAlta,
  gravatai,
  ijui,
  lajeado,
  novoHamburgo,
  passoFundo,
  pelotas,
  portoAlegre,
  rioGrande,
  staCruzDoSul,
  staMaria,
  staRosa,
  livramento,
  santiago,
  stoAngelo,
  uruguaiana;

export const cities = [
  (bage = {
    nomeCidade: "Bagé",
    cidadesAtendidas: [
      { name: "Bagé", mandado: true, UAA: "" },
      { name: "Candiota", mandado: true, UAA: "" },
      { name: "Hulha Negra", mandado: true, UAA: "" },
    ],
  }),
  (bentoGoncalves = {
    nomeCidade: "Bento Gonçalves",
    cidadesAtendidas: [
      { name: "Barão", mandado: true, UAA: "" },
      { name: "Bento Gonçalves", mandado: true, UAA: "" },
      { name: "Boa Vista do Sul", mandado: true, UAA: "" },
      { name: "Carlos Barbosa", mandado: true, UAA: "" },
      { name: "Coronel Pilar", mandado: true, UAA: "" },
      { name: "Cotiporã", mandado: true, UAA: "" },
      { name: "Dois Lajeados", mandado: true, UAA: "" },
      { name: "Garibaldi", mandado: true, UAA: "" },
      { name: "Monte Belo do Sul", mandado: true, UAA: "" },
      { name: "Pinto Bandeira", mandado: true, UAA: "" },
      { name: "Santa Teresa", mandado: true, UAA: "" },
      { name: "São Valentim do Sul", mandado: true, UAA: "" },
      { name: "São Vendelino", mandado: true, UAA: "" },
      { name: "Veranópolis", mandado: true, UAA: "" },
      { name: "Vila Flores", mandado: true, UAA: "" },
    ],
  }),
  (cachoeiraDoSul = {
    nomeCidade: "Cachoeira do Sul",
    cidadesAtendidas: [
      { name: "Cachoeira do Sul", mandado: true, UAA: "" },
      { name: "Cerro Branco", mandado: true, UAA: "" },
      { name: "Novo Cabrais", mandado: true, UAA: "" },
      { name: "Paraíso do Sul", mandado: true, UAA: "" },
    ],
  }),
  (canoas = {
    nomeCidade: "Canoas",
    cidadesAtendidas: [
      { name: "Canoas", mandado: true, UAA: "" },
      { name: "Esteio", mandado: true, UAA: "" },
      { name: "Nova Santa Rita", mandado: true, UAA: "" },
      { name: "Sapucaia do Sul", mandado: true, UAA: "" },
    ],
  }),
  (capaoDaCanoa = {
    nomeCidade: "Capão da Canoa",
    cidadesAtendidas: [
      { name: "Arroio do Sal", mandado: true, UAA: "UAA de Torres" },
      { name: "Capão da Canoa", mandado: true, UAA: "" },
      { name: "Caraá", mandado: true, UAA: "" },
      { name: "Cidreira", mandado: true, UAA: "" },
      { name: "Dom Pedro de Alcântara", mandado: false, UAA: "UAA de Torres" },
      { name: "Imbé", mandado: true, UAA: "" },
      { name: "Itati", mandado: true, UAA: "" },
      { name: "Mampituba", mandado: false, UAA: "UAA de Torres" },
      { name: "Maquiné", mandado: true, UAA: "" },
      { name: "Morrinhos do Sul", mandado: false, UAA: "UAA de Torres" },
      { name: "Osório", mandado: true, UAA: "" },
      { name: "Terra de Areia", mandado: true, UAA: "" },
      { name: "Torres", mandado: true, UAA: "UAA de Torres" },
      { name: "Tramandaí", mandado: true, UAA: "" },
      { name: "Três Cachoeiras", mandado: true, UAA: "UAA de Torres" },
      { name: "Três Forquilhas", mandado: true, UAA: "UAA de Torres" },
      { name: "Xangri-lá", mandado: true, UAA: "" },
    ],
  }),
  (carazinho = {
    nomeCidade: "Carazinho",
    cidadesAtendidas: [
      { name: "Almirante Tamandaré do Sul", mandado: true, UAA: "" },
      { name: "Alto Alegre", mandado: false, UAA: "UAA de Soledade" },
      { name: "Barra Funda", mandado: true, UAA: "" },
      { name: "Barros Cassal", mandado: false, UAA: "UAA de Soledade" },
      { name: "Campos Borges", mandado: false, UAA: "UAA de Soledade" },
      { name: "Carazinho", mandado: true, UAA: "" },
      { name: "Chapada", mandado: true, UAA: "" },
      { name: "Colorado", mandado: true, UAA: "" },
      { name: "Coqueiros do Sul", mandado: true, UAA: "" },
      { name: "Espumoso", mandado: true, UAA: "UAA de Soledade" },
      { name: "Fontoura Xavier", mandado: false, UAA: "UAA de Soledade" },
      { name: "Ibirapuitã", mandado: false, UAA: "UAA de Soledade" },
      { name: "Lagoa dos Três Cantos", mandado: true, UAA: "" },
      { name: "Lagoão", mandado: false, UAA: "UAA de Soledade" },
      { name: "Mormaço", mandado: true, UAA: "UAA de Soledade" },
      { name: "Não Me Toque", mandado: true, UAA: "" },
      { name: "Nova Boa Vista", mandado: true, UAA: "" },
      { name: "Rondinha", mandado: true, UAA: "" },
      { name: "Saldanha Marinho", mandado: true, UAA: "" },
      { name: "Santa Bárbara do Sul", mandado: true, UAA: "" },
      { name: "Santo Antônio do Planalto", mandado: true, UAA: "" },
      { name: "São José do Herval", mandado: false, UAA: "UAA de Soledade" },
      { name: "Sarandi", mandado: true, UAA: "" },
      { name: "Soledade", mandado: false, UAA: "UAA de Soledade" },
      { name: "Tapera", mandado: true, UAA: "" },
      { name: "Tio Hugo", mandado: true, UAA: "" },
      { name: "Tunas", mandado: false, UAA: "UAA de Soledade" },
      { name: "Victor Graef", mandado: true, UAA: "" },
    ],
  }),
  (caxiasDoSul = {
    nomeCidade: "Caxias do Sul",
    cidadesAtendidas: [
      { name: "Alto Feliz", mandado: true, UAA: "" },
      { name: "Antônio Prado", mandado: true, UAA: "" },
      { name: "Bom Jesus", mandado: false, UAA: "UAA de Vacaria" },
      { name: "Campestre da Serra", mandado: false, UAA: "UAA de Vacaria" },
      { name: "Canela", mandado: false, UAA: "UAA de Gramado e Canela" },
      { name: "Caxias do Sul", mandado: true, UAA: "" },
      { name: "Esmeralda", mandado: false, UAA: "UAA de Vacaria" },
      { name: "Farroupilha", mandado: true, UAA: "" },
      { name: "Feliz", mandado: true, UAA: "" },
      { name: "Flores da Cunha", mandado: true, UAA: "" },
      { name: "Gramado", mandado: false, UAA: "UAA de Gramado e Canela" },
      { name: "Ipê", mandado: true, UAA: "" },
      { name: "Jaquirana", mandado: false, UAA: "UAA de Vacaria" },
      {
        name: "Monte Alegre dos Campos",
        mandado: false,
        UAA: "UAA de Vacaria",
      },
      { name: "Muitos Capões", mandado: false, UAA: "UAA de Vacaria" },
      { name: "Nova Pádua", mandado: true, UAA: "" },
      {
        name: "Nova Petrópolis",
        mandado: true,
        UAA: "UAA de Gramado e Canela",
      },
      { name: "Nova Roma do Sul", mandado: true, UAA: "" },
      { name: "Picada Café", mandado: true, UAA: "UAA de Gramado e Canela" },
      { name: "Pinhal da Serra", mandado: false, UAA: "UAA de Vacaria" },
      { name: "São José dos Ausentes", mandado: false, UAA: "UAA de Vacaria" },
      { name: "São Marcos", mandado: true, UAA: "" },
      { name: "Vacaria", mandado: false, UAA: "UAA de Vacaria" },
      { name: "Vale Real", mandado: true, UAA: "" },
    ],
  }),
  (cruzAlta = {
    nomeCidade: "Cruz Alta",
    cidadesAtendidas: [
      { name: "Boa Vista do Cadeado", mandado: true, UAA: "" },
      { name: "Boa Vista do Incra", mandado: true, UAA: "" },
      { name: "Cruz Alta", mandado: true, UAA: "" },
      { name: "Fortaleza dos Valos", mandado: true, UAA: "" },
      { name: "Ibirubá", mandado: true, UAA: "" },
      { name: "Panambi", mandado: true, UAA: "" },
      { name: "Pejuçara", mandado: true, UAA: "" },
    ],
  }),
  (erechim = {
    nomeCidade: "Erechim",
    cidadesAtendidas: [
      { name: "Aratiba", mandado: true, UAA: "" },
      { name: "Áurea", mandado: true, UAA: "" },
      { name: "Barão de Cotegipe", mandado: true, UAA: "" },
      { name: "Barra do Rio Azul", mandado: true, UAA: "" },
      { name: "Benjamin Constant do Sul", mandado: true, UAA: "" },
      { name: "Campinas do Sul", mandado: true, UAA: "" },
      { name: "Carlos Gomes", mandado: true, UAA: "" },
      { name: "Centenário", mandado: true, UAA: "" },
      { name: "Charrua", mandado: true, UAA: "" },
      { name: "Cruzaltense", mandado: true, UAA: "" },
      { name: "Erebango", mandado: true, UAA: "" },
      { name: "Erechim", mandado: true, UAA: "" },
      { name: "Estação", mandado: true, UAA: "" },
      { name: "Floriano Peixoto", mandado: true, UAA: "" },
      { name: "Gaurama", mandado: true, UAA: "" },
      { name: "Getúlio Vargas", mandado: true, UAA: "" },
      { name: "Ipiranga do Sul", mandado: true, UAA: "" },
      { name: "Itatiba do Sul", mandado: true, UAA: "" },
      { name: "Jacutinga", mandado: true, UAA: "" },
      { name: "Marcelino Ramos", mandado: true, UAA: "" },
      { name: "Mariano Moro", mandado: true, UAA: "" },
      { name: "Paulo Bento", mandado: true, UAA: "" },
      { name: "Ponte Preta", mandado: true, UAA: "" },
      { name: "Quatro Irmãos", mandado: true, UAA: "" },
      { name: "São Valentim", mandado: true, UAA: "" },
      { name: "Severiano de Almeida", mandado: true, UAA: "" },
      { name: "Três Arroios", mandado: true, UAA: "" },
      { name: "Viadutos", mandado: true, UAA: "" },
    ],
  }),
  (gravatai = {
    nomeCidade: "Gravataí",
    cidadesAtendidas: [
      { name: "Cachoeirinha", mandado: true, UAA: "" },
      { name: "Glorinha", mandado: true, UAA: "" },
      { name: "Gravataí", mandado: true, UAA: "" },
      { name: "Santo Antônio da Patrulha", mandado: true, UAA: "" },
    ],
  }),
  (ijui = {
    nomeCidade: "Ijuí",
    cidadesAtendidas: [
      { name: "Ajuricaba", mandado: true, UAA: "" },
      { name: "Augusto Pestana", mandado: true, UAA: "" },
      { name: "Bozano", mandado: true, UAA: "" },
      { name: "Catuípe", mandado: true, UAA: "" },
      { name: "Chiapeta", mandado: true, UAA: "" },
      { name: "Coronel Barros", mandado: true, UAA: "" },
      { name: "Ijuí", mandado: true, UAA: "" },
      { name: "Jóia", mandado: true, UAA: "" },
      { name: "Nova Ramada", mandado: true, UAA: "" },
    ],
  }),
  (lajeado = {
    nomeCidade: "Lajeado",
    cidadesAtendidas: [
      { name: "Arroio do Meio", mandado: true, UAA: "" },
      { name: "Bom Retiro do Sul", mandado: true, UAA: "" },
      { name: "Canudos do Vale", mandado: true, UAA: "" },
      { name: "Capitão", mandado: true, UAA: "" },
      { name: "Colinas", mandado: true, UAA: "" },
      { name: "Coqueiro Baixo", mandado: true, UAA: "" },
      { name: "Cruzeiro do Sul", mandado: true, UAA: "" },
      { name: "Doutor Ricardo", mandado: true, UAA: "" },
      { name: "Encantado", mandado: true, UAA: "" },
      { name: "Estrela", mandado: true, UAA: "" },
      { name: "Forquetinha", mandado: true, UAA: "" },
      { name: "Imigrante", mandado: true, UAA: "" },
      { name: "Lajeado", mandado: true, UAA: "" },
      { name: "Marques de Souza", mandado: true, UAA: "" },
      { name: "Muçum", mandado: true, UAA: "" },
      { name: "Nova Bréscia", mandado: true, UAA: "" },
      { name: "Poço das Antas", mandado: true, UAA: "" },
      { name: "Pouso Novo", mandado: true, UAA: "" },
      { name: "Progresso", mandado: true, UAA: "" },
      { name: "Relvado", mandado: true, UAA: "" },
      { name: "Roca Sales", mandado: true, UAA: "" },
      { name: "Santa Clara do Sul", mandado: true, UAA: "" },
      { name: "Sério", mandado: true, UAA: "" },
      { name: "Teutônia", mandado: true, UAA: "" },
      { name: "Travesseiro", mandado: true, UAA: "" },
      { name: "Vespasiano Corrêa", mandado: true, UAA: "" },
      { name: "Westfália", mandado: true, UAA: "" },
    ],
  }),
  (novoHamburgo = {
    nomeCidade: "Novo Hamburgo",
    cidadesAtendidas: [
      { name: "Araricá", mandado: true, UAA: "" },
      { name: "Bom Princípio", mandado: true, UAA: "" },
      { name: "Campo Bom", mandado: true, UAA: "" },
      { name: "Dois Irmãos", mandado: true, UAA: "" },
      { name: "Estância Velha", mandado: true, UAA: "" },
      { name: "Igrejinha", mandado: true, UAA: "UAA de Gramado e Canela" },
      { name: "Ivoti", mandado: true, UAA: "" },
      { name: "Lindolfo Collor", mandado: true, UAA: "" },
      { name: "Linha Nova", mandado: true, UAA: "" },
      { name: "Morro Reuter", mandado: true, UAA: "" },
      { name: "Nova Hartz", mandado: true, UAA: "" },
      { name: "Novo Hamburgo", mandado: true, UAA: "" },
      { name: "Parobé", mandado: true, UAA: "" },
      { name: "Portão", mandado: true, UAA: "" },
      { name: "Presidente Lucena", mandado: true, UAA: "" },
      { name: "Santa Maria do Herval", mandado: true, UAA: "" },
      { name: "São José do Hortêncio", mandado: true, UAA: "" },
      { name: "São Leopoldo", mandado: true, UAA: "UAA de São Leopoldo" },
      { name: "São Sebastião do Caí", mandado: true, UAA: "" },
      { name: "Sapiranga", mandado: true, UAA: "" },
      { name: "Taquara", mandado: true, UAA: "" },
      { name: "Três Coroas", mandado: true, UAA: "UAA de Gramado e Canela" },
    ],
  }),
  (palmeiraDasMissoes = {
    nomeCidade: "Palmeira das Missoes",
    cidadesAtendidas: [
      { name: "Boa Vista das Missões", mandado: true, UAA: "" },
      { name: "Caiçara", mandado: false, UAA: "UAA de Frederico Westphalen" },
      { name: "Cerro Grande", mandado: true, UAA: "" },
      { name: "Coronel Bicaco", mandado: true, UAA: "" },
      { name: "Dois Irmãos das Missões", mandado: true, UAA: "" },
      {
        name: "Frederico Westphalen",
        mandado: false,
        UAA: "UAA de FredericoWestphalen ",
      },
      { name: "Iraí", mandado: false, UAA: "UAA de Frederico Westphalen" },
      { name: "Jaboticaba", mandado: true, UAA: "" },
      { name: "Lajeado do Bugre", mandado: true, UAA: "" },
      { name: "Novo Barreiro", mandado: true, UAA: "" },
      { name: "Novo Tiradentes", mandado: true, UAA: "" },
      { name: "Palmeira das Missões", mandado: true, UAA: "" },
      {
        name: "Palmitinho",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      { name: "Pinhal", mandado: true, UAA: "" },
      {
        name: "Pinheirinho do Vale",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      { name: "Redentora", mandado: true, UAA: "" },
      { name: "Sagrada Família", mandado: true, UAA: "" },
      { name: "São José das Missões", mandado: true, UAA: "" },
      { name: "São Pedro das Missões", mandado: true, UAA: "" },
      { name: "Seberi", mandado: true, UAA: "" },
      {
        name: "Taquaruçu do Sul",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      {
        name: "Vicente Dutra",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      {
        name: "Vista Alegre",
        mandado: true,
        UAA: "UAA de Frederico Westphalen",
      },
    ],
  }),
  (passoFundo = {
    nomeCidade: "Passo Fundo",
    cidadesAtendidas: [
      { name: "Água Santa", mandado: true, UAA: "" },
      { name: "Camargo", mandado: true, UAA: "" },
      { name: "Coxilha", mandado: true, UAA: "" },
      { name: "Ernestina", mandado: true, UAA: "" },
      { name: "Gentil", mandado: true, UAA: "" },
      { name: "Marau", mandado: true, UAA: "" },
      { name: "Mato Castelhano", mandado: true, UAA: "" },
      { name: "Passo Fundo", mandado: true, UAA: "" },
      { name: "Pontão", mandado: true, UAA: "" },
      { name: "Sertão", mandado: true, UAA: "" },
      { name: "Tapejara", mandado: true, UAA: "" },
      { name: "Vila Lângaro", mandado: true, UAA: "" },
      { name: "Vila Maria", mandado: true, UAA: "" },
      { name: "Nicolau Vergueiro", mandado: true, UAA: "" },
    ],
  }),
  (pelotas = {
    nomeCidade: "Pelotas",
    cidadesAtendidas: [
      { name: "Arroio do Padre", mandado: true, UAA: "" },
      { name: "Arroio Grande", mandado: false, UAA: "UAA de Jaguarão" },
      { name: "Canguçu", mandado: true, UAA: "" },
      { name: "Capão do Leão", mandado: true, UAA: "" },
      { name: "Cerrito", mandado: true, UAA: "" },
      { name: "Herval", mandado: false, UAA: "UAA de Jaguarão" },
      { name: "Jaguarão", mandado: false, UAA: "UAA de Jaguarão" },
      { name: "Morro Redondo", mandado: true, UAA: "" },
      { name: "Pedro Osório", mandado: true, UAA: "" },
      { name: "Pelotas", mandado: true, UAA: "" },
      { name: "Turuçu", mandado: true, UAA: "" },
    ],
  }),
  (portoAlegre = {
    nomeCidade: "Porto Alegre",
    cidadesAtendidas: [
      { name: "Alvorada", mandado: true, UAA: "" },
      { name: "Arambaré", mandado: true, UAA: "UAA de Camaquã" },
      { name: "Arroio dos Ratos", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Barão do Triunfo", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Brochier", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Butiá", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Camaquã", mandado: false, UAA: "UAA de Camaquã" },
      { name: "Capela de Santana", mandado: true, UAA: "UAA de Montenegro" },
      { name: "Charqueadas", mandado: true, UAA: "UAA de São Jerônimo" },
      { name: "Chuvisca", mandado: false, UAA: "UAA de Camaquã" },
      { name: "Cristal", mandado: false, UAA: "UAA de Camaquã" },
      { name: "Dom Feliciano", mandado: false, UAA: "UAA de Camaquã" },
      { name: "Eldorado do Sul", mandado: true, UAA: "" },
      { name: "Fazenda Vilanova", mandado: false, UAA: "UAA de Montenegro" },
      { name: "General Câmara", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Guaíba", mandado: true, UAA: "" },
      { name: "Harmonia", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Maratá", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Minas do Leão", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Montenegro", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Pareci Novo", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Paverama", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Porto Alegre", mandado: true, UAA: "" },
      { name: "Salvador do Sul", mandado: false, UAA: "UAA de Montenegro" },
      { name: "São Jerônimo", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "São José do Sul", mandado: false, UAA: "UAA de Montenegro" },
      { name: "São Pedro da Serra", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Tabaí", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Taquari", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Triunfo", mandado: false, UAA: "UAA de São Jerônimo" },
      { name: "Tupandi", mandado: false, UAA: "UAA de Montenegro" },
      { name: "Viamão", mandado: true, UAA: "" },
    ],
  }),
  (rioGrande = {
    nomeCidade: "Rio Grande",
    cidadesAtendidas: [
      { name: "Chuí", mandado: false, UAA: "UAA de Santa Vitória do Palmar" },
      { name: "Rio Grande", mandado: true, UAA: "" },
      {
        name: "Santa Vitória do Palmar",
        mandado: false,
        UAA: "UAA de Santa Vitória do Palmar",
      },
      { name: "São José do Norte", mandado: true, UAA: "" },
    ],
  }),
  (staCruzDoSul = {
    nomeCidade: "Santa Cruz do Sul",
    cidadesAtendidas: [
      { name: "Candelária", mandado: true, UAA: "" },
      { name: "Herveiras", mandado: true, UAA: "" },
      { name: "Mato Leitão", mandado: true, UAA: "" },
      { name: "Passo do Sobrado", mandado: true, UAA: "" },
      { name: "Rio Pardo", mandado: true, UAA: "" },
      { name: "Santa Cruz do Sul", mandado: true, UAA: "" },
      { name: "Sinimbu", mandado: true, UAA: "" },
      { name: "Vale do Sol", mandado: true, UAA: "" },
      { name: "Vale Verde", mandado: true, UAA: "" },
      { name: "Venâncio Aires", mandado: true, UAA: "" },
      { name: "Vera Cruz", mandado: true, UAA: "" },
      { name: "Pantano Grande", mandado: true, UAA: "" },
    ],
  }),
  (staMaria = {
    nomeCidade: "Santa Maria",
    cidadesAtendidas: [
      { name: "Dilermando de Aguiar", mandado: true, UAA: "" },
      { name: "Faxinal do Soturno", mandado: true, UAA: "" },
      { name: "Itaara", mandado: true, UAA: "" },
      { name: "Ivorá", mandado: true, UAA: "" },
      { name: "Restinga Seca", mandado: true, UAA: "" },
      { name: "Santa Maria", mandado: true, UAA: "" },
      { name: "São João do Polêsine", mandado: true, UAA: "" },
      { name: "São Martinho da Serra", mandado: true, UAA: "" },
      { name: "São Pedro do Sul", mandado: true, UAA: "" },
      { name: "Silveira Martins", mandado: true, UAA: "" },
    ],
  }),
  (staRosa = {
    nomeCidade: "Santa Rosa",
    cidadesAtendidas: [
      { name: "Alecrim", mandado: true, UAA: "" },
      { name: "Boa Vista do Buricá", mandado: true, UAA: "" },
      { name: "Campina das Missões", mandado: true, UAA: "" },
      { name: "Cândido Godói", mandado: true, UAA: "" },
      { name: "Doutor Maurício Cardoso", mandado: true, UAA: "" },
      { name: "Horizontina", mandado: true, UAA: "" },
      { name: "Independência", mandado: true, UAA: "" },
      { name: "Novo Machado", mandado: true, UAA: "" },
      { name: "Porto Mauá", mandado: true, UAA: "" },
      { name: "Porto Vera Cruz", mandado: true, UAA: "" },
      { name: "Santa Rosa", mandado: true, UAA: "" },
      { name: "Santo Cristo", mandado: true, UAA: "" },
      { name: "São José do Inhacorá", mandado: true, UAA: "" },
      { name: "Três de Maio", mandado: true, UAA: "" },
      { name: "Tucunduva", mandado: true, UAA: "" },
      { name: "Tuparendi", mandado: true, UAA: "" },
      { name: "São Paulo das Missões", mandado: true, UAA: "" },
    ],
  }),
  (livramento = {
    nomeCidade: "Sant'Ana do Livramento",
    cidadesAtendidas: [
      { name: "Sant'Ana do Livramento", mandado: true, UAA: "" },
    ],
  }),
  (santiago = {
    nomeCidade: "Santiago",
    cidadesAtendidas: [
      { name: "Capão do Cipó", mandado: true, UAA: "" },
      { name: "Maçambará", mandado: false, UAA: "UAA de São Borja" },
      { name: "Nova Esperança do Sul", mandado: true, UAA: "" },
      { name: "Santiago", mandado: true, UAA: "" },
      { name: "São Borja", mandado: false, UAA: "UAA de São Borja" },
      { name: "Unistalda", mandado: true, UAA: "" },
      { name: "Jaguari", mandado: true, UAA: "" },
      { name: "São Francisco de Assis", mandado: true, UAA: "" },
    ],
  }),
  (stoAngelo = {
    nomeCidade: "Santo Ângelo",
    cidadesAtendidas: [
      { name: "Bossoroca", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      { name: "Caibaté", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      { name: "Cerro Largo", mandado: true, UAA: "" },
      {
        name: "Dezesseis de Novembro",
        mandado: false,
        UAA: "UAA de São Luiz Gonzaga",
      },
      { name: "Entre Ijuis", mandado: true, UAA: "" },
      { name: "Eugênio de Castro", mandado: true, UAA: "" },
      { name: "Garruchos", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      { name: "Giruá", mandado: true, UAA: "" },
      { name: "Guarani das Missões", mandado: true, UAA: "" },
      { name: "Mato Queimado", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      { name: "Pirapó", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      { name: "Rolador", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      {
        name: "Roque Gonzales",
        mandado: false,
        UAA: "UAA de São Luiz Gonzaga",
      },
      { name: "Santo Ângelo", mandado: true, UAA: "" },
      {
        name: "Santo Antônio das Missões",
        mandado: false,
        UAA: "UAA de São Luiz Gonzaga",
      },
      {
        name: "São Luiz Gonzaga",
        mandado: false,
        UAA: "UAA de São Luiz Gonzaga",
      },
      { name: "São Miguel das Missões", mandado: true, UAA: "" },
      { name: "São Nicolau", mandado: false, UAA: "UAA de São Luiz Gonzaga" },
      {
        name: "São Pedro do Butiá",
        mandado: false,
        UAA: "UAA de São Luiz Gonzaga",
      },
      { name: "Senador Salgado Filho", mandado: true, UAA: "" },
      { name: "Sete de Setembro", mandado: true, UAA: "" },
      { name: "Vitória das Missões", mandado: true, UAA: "" },
    ],
  }),
  (uruguaiana = {
    nomeCidade: "Uruguaiana",
    cidadesAtendidas: [
      { name: "Alegrete", mandado: false, UAA: "UAA de Alegrete" },
      { name: "Itaqui", mandado: false, UAA: "UAA de Itaqui" },
      { name: "Manoel Viana", mandado: false, UAA: "UAA de Alegrete" },
      { name: "Uruguaiana", mandado: true, UAA: "" },
    ],
  }),
];
