/* eslint-disable @typescript-eslint/no-unused-vars */
let erechim;
let palmeiraDasMissoes;

export const cities = [
  (erechim = {
    nomeCidade: "Erechim",
    cidadesAtendidas: [
      { name: "Aratiba", mandado: true, UAA: "" },
      { name: "Áurea", mandado: true, UAA: "" },
      { name: "Barão de Cotegipe", mandado: true, UAA: "" },
      { name: "Barra do Rio Azul", mandado: true, UAA: "" },
      { name: "Benjamin Constant do Sul", mandado: true, UAA: "" },
      { name: "Campinas do Sul", mandado: true, UAA: "" },
      { name: "Carlos Gomes", mandado: true, UAA: "" },
      { name: "Centenário", mandado: true, UAA: "" },
      { name: "Charrua", mandado: true, UAA: "" },
      { name: "Cruzaltense", mandado: true, UAA: "" },
      { name: "Erebango", mandado: true, UAA: "" },
      { name: "Erechim", mandado: true, UAA: "" },
      { name: "Estação", mandado: true, UAA: "" },
      { name: "Floriano Peixoto", mandado: true, UAA: "" },
      { name: "Gaurama", mandado: true, UAA: "" },
      { name: "Getúlio Vargas", mandado: true, UAA: "" },
      { name: "Ipiranga do Sul", mandado: true, UAA: "" },
      { name: "Itatiba do Sul", mandado: true, UAA: "" },
      { name: "Jacutinga", mandado: true, UAA: "" },
      { name: "Marcelino Ramos", mandado: true, UAA: "" },
      { name: "Mariano Moro", mandado: true, UAA: "" },
      { name: "Paulo Bento", mandado: true, UAA: "" },
      { name: "Ponte Preta", mandado: true, UAA: "" },
      { name: "Quatro Irmãos", mandado: true, UAA: "" },
      { name: "São Valentim", mandado: true, UAA: "" },
      { name: "Severiano de Almeida", mandado: true, UAA: "" },
      { name: "Três Arroios", mandado: true, UAA: "" },
      { name: "Viadutos", mandado: true, UAA: "" },
    ],
  }),
  (palmeiraDasMissoes = {
    nomeCidade: "Palmeira das Missoes",
    cidadesAtendidas: [
      { name: "Boa Vista das Missões", mandado: true, UAA: "" },
      { name: "Caiçara", mandado: false, UAA: "UAA de Frederico Westphalen" },
      { name: "Cerro Grande", mandado: true, UAA: "" },
      { name: "Coronel Bicaco", mandado: true, UAA: "" },
      { name: "Dois Irmãos das Missões", mandado: true, UAA: "" },
      {
        name: "Frederico Westphalen",
        mandado: false,
        UAA: "UAA de FredericoWestphalen ",
      },
      { name: "Iraí", mandado: false, UAA: "UAA de Frederico Westphalen" },
      { name: "Jaboticaba", mandado: true, UAA: "" },
      { name: "Lajeado do Bugre", mandado: true, UAA: "" },
      { name: "Novo Barreiro", mandado: true, UAA: "" },
      { name: "Novo Tiradentes", mandado: true, UAA: "" },
      { name: "Palmeira das Missões", mandado: true, UAA: "" },
      {
        name: "Palmitinho",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      { name: "Pinhal", mandado: true, UAA: "" },
      {
        name: "Pinheirinho do Vale",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      { name: "Redentora", mandado: true, UAA: "" },
      { name: "Sagrada Família", mandado: true, UAA: "" },
      { name: "São José das Missões", mandado: true, UAA: "" },
      { name: "São Pedro das Missões", mandado: true, UAA: "" },
      { name: "Seberi", mandado: true, UAA: "" },
      {
        name: "Taquaruçu do Sul",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      {
        name: "Vicente Dutra",
        mandado: false,
        UAA: "UAA de Frederico Westphalen",
      },
      {
        name: "Vista Alegre",
        mandado: true,
        UAA: "UAA de Frederico Westphalen",
      },
    ],
  }),
];
